wechat_app_id: "wx7ed25ed89db628bd"
wechat_secret: "e60dfaa4f3118db66c42c61bf53dfd93"
wechat_token:  "Token"
wechat_encoding_aes_key: "EncodingAESKey"
wechat_trusted_domain_fullname: "http://bluefairypark.cn"

# following is optional if you don't need wechat pay
wechat_pay_mch_id: "1461671802"
wechat_pay_api_key: "7db23d0870fbc5631ef6b4db781b1670"
wechat_pay_notify_url: "http://bluefairypark.cn/m/wx_notify"