default: &default
  encoding: utf8
  adapter: mysql2
  pool: 5
  host: localhost
  username: root
  password: 861117

development:
  <<: *default
  database: dql_sports

production:
  <<: *default
  username: stephen
  password: ljh86wss90
  database: dql_sports
