default: &default
  encoding: utf8
  adapter: postgis
  pool: 5
  host: localhost
  username: stephen
  password: 

development:
  <<: *default
  database: dql_sports

test:
  <<: *default
  database: dql_sports

production:
  <<: *default
  username: stephen
  password: ljh86wss90
  database: dql_sports
