default: &default
  encoding: utf8
  adapter: postgis
  pool: 5
  timeout: 5000
  host: localhost
  schema_search_path: public

production:
  <<: *default
  username: ruzun
  password: ljh86wss90
  su_username: postgres     # a superuser for the database
  su_password: 7oL-6Zh-Dzw-ZwR  # the superuser's password
  database: ruzun
