default: &default
  encoding: utf8
  adapter: postgis
  pool: 5
  timeout: 5000
  host: localhost
  schema_search_path: public

development:
  <<: *default
  username: stephen
  password:
  database: dql_sports

production:
  <<: *default
  username: stephen
  password: ljh86wss90
  database: dql_sports
